version: '3'

services:
  myapp:
    build: .
    container_name: myapp
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html

  postgres:
    image: "postgres:latest"
    container_name: container-postgres
    restart: always
    environment:
      POSTGRES_DB: db_pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: ./website
   # image: php
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "8888:80"